# common reusable block for airflow services
x-airflow-common: &airflow-common
  build: . #added with the dockerfile in the root of the project
  env_file: .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/airflow_db
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
    PYTHONPATH: /opt/airflow
  volumes:
    - ./dags:/opt/airflow/dags               # the DAG files
    - ./extract:/opt/airflow/extract         # Python extract scripts
    - ./transform:/opt/airflow/transform     # dbt project
    - ./data:/opt/airflow/data               # raw JSON landing zone
    - airflow_logs:/opt/airflow/logs
  depends_on:
    postgres:
      condition: service_healthy

services:

  # ── 1. PostgreSQL ──────────────────────
  postgres:
    image: postgres:15
    container_name: pipeline_postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"                          
    volumes:
      - postgres_data:/var/lib/postgresql/data   
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql  # runs once on first start
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 10s

  # ── 2. Airflow webserver ─────────────
  airflow-webserver:
    <<: *airflow-common
    container_name: pipeline_airflow_webserver
    command: webserver
    ports:
      - "8080:8080"                          
    restart: unless-stopped

  # ── 3. Airflow scheduler ────────────
  airflow-scheduler:
    <<: *airflow-common
    container_name: pipeline_airflow_scheduler
    command: scheduler
    restart: unless-stopped

  # ── 4. Airflow init (runs once) ─────
  airflow-init:
    <<: *airflow-common
    container_name: pipeline_airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db upgrade
        airflow users create \
          --username admin \
          --password admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com
    restart: on-failure

  # ── Metabase ───────────────────────
  metabase:
    image: metabase/metabase:latest
    container_name: pipeline_metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

# ── dbt ───────────────────────────────
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.0
    container_name: pipeline_dbt
    volumes:
      - ./transform/marketing_transform:/usr/app/dbt
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt
    depends_on:
      postgres:
        condition: service_healthy
    working_dir: /usr/app/dbt
    ports:
      - "8081:8080"        # ← add this line
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:    # Postgres data managed by Docker (inside WSL)
  airflow_logs:     # Airflow task logs
  metabase_data:    # Metabase data (inside WSL)